#!/bin/bash

PYENV=.envcursor
PYENV_CALL=$PYENV/bin/python

# figure out which python to use 
if [[ ! -f $PYENV_CALL ]]; then 
  unset PYENV_CALL
  # search for common python aliases
  if [[ -z $python ]]; then
    calls=(python3 python2 python)
    for call in ${calls[@]}; do
      type $call &> /dev/null
      has_python=$?
      if [[ $has_python -eq 0 ]]; then
        PYENV_CALL=$call
        break
      fi
    done
    if [[ -z $PYENV_CALL ]]; then
      echo "[ERROR] cannot find python"
      exit 1
    fi
  else
    PYENV_CALL=$python
  fi
fi

# run within the full anaconda environment
if [[ "$1" == "envrun" ]]; then
   if [[ ! -f $PYENV_CALL ]]; then 
      echo "[ERROR] no conda environment" && exit 1;
   fi
   # hardcoded path to miniconda (different on osx?)
   source conda/etc/profile.d/conda.sh
   conda activate $(readlink .envcursor)
   ${@:2}
# run something in the anaconda bin but not the full environment
elif [[ "$1" == "run" ]]; then
   PATH=$PYENV/bin:$PATH
   ${@:2}
# standard interface does not have the full environment
else 
  $PYENV_CALL -B ${CLI:-cli.py} $@
fi
