#! use a name and put this in some grab-bag file?
script: |
  # set the modeller license key
  import pkgutil,os
  import glob
  package = pkgutil.get_loader("modeller")
  if not package: raise Exception('cannot load modeller from pkgutil')
  config_fn = os.path.join(os.path.dirname(package.path),'config.py')
  if not os.path.isfile(config_fn): 
    raise Exception('cannot find modeller config')
  key = input("enter the modeller license key: ")
  if key:
    with open(config_fn,'a') as fp: 
      fp.write('\nlicense = r"%s"'%key.strip())
  import modeller
  print('status imported modeller from: %s'%modeller.__file__)
